[package]
name = "imp_ods"
version = "0.1.0"
authors = ["Steve Canham <stevecanham@outlook.com>"]
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "imp_ods"

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
thiserror = "2.0.20"
sqlx = { version = "0.8.6", features = [ "runtime-tokio", "postgres", "macros", "chrono" ] }
tokio = { version = "1.53.1", features = ["macros", "rt"]}
clap = { version = "4.6.7", features = ["cargo"] }
regex = "1.13.1"
chrono = { version = "0.4.45", features = ["clock"] }
log = "0.4.34"
log4rs = "1.4.0"
toml = "0.9.12"
csv = "1.4.0"
directories = "6.0.0"
